### PR TITLE
Units - VIP Suit V2

### PR DESCRIPTION
**Pull request by Mike-MF**
Evrik from 3CB did a return contribution for Theseus Services:
> This is the updated VIP Suit 
> I've fixed up its hidden texture selections, created some slightly different texture variants with different shirt colours and added working wound textures to it so that when you shoot the unit, he actually shows blood.

Converted everything I could find, works in-game and it does show blood, it's quite nice.

It's also quite easy to retexture should we ever want to now (along with the ones Evrik sent over)

### CODE REVIEW

**Comment by jonpas** [comment]
Closes #15.

**Review by jonpas — APPROVED** [review]

**Comment by jonpas** [comment]
Who allowed you to merge this? rvmats contain tabs.

**Comment by Mike-MF** [comment]
You contain tabs.

**Comment by jonpas** [comment]
#204

**Pull request merged**
