### PR TITLE
Changes for armake

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Make necessary changes for building with armake
- Add a Makefile
- Fixes `CfgWeapons` rapification issues due to superficial semi-colons (thanks @KoffeinFlummi)

Todo:
- Verify macros in model.cfg work (can be binarized when binarizing model itself, seems to work even without include)

### CODE REVIEW

**Comment by SyMP2005** [comment]
Ooooh, is it close?

**Comment by jonpas** [comment]
https://forums.bistudio.com/topic/190572-armake/

**Comment by jonpas** [comment]
Will get converted to HEMTT.

**Comment by jonpas** [comment]
HEMTT configuration now on `master`.

**Pull request closed without merging**
